apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: crossplane-service-broker
resources:
  - deployment-redis.yaml
  - rbac.yaml
  - service_account.yaml
  - service-redis.yaml
