apiVersion: v1
kind: Service
metadata:
  name: crossplane-service-broker-redis
  labels:
    app.kubernetes.io/instance: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: redis
  ports:
    - name: http
      port: 80
      targetPort: http
