---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane-service-broker-redis
  namespace: crossplane-service-broker
spec:
  template:
    spec:
      containers:
        - name: crossplane-service-broker
          image: $E2E_IMAGE
          imagePullPolicy: Never
          env:
            - name: OSB_USERNAME
              value: test
            - name: OSB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crossplane-service-broker
                  key: password
            - name: OSB_NAMESPACE
              value: test
            - name: OSB_SERVICE_IDS
              value: test
