---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossplane-service-broker-redis
  namespace: crossplane-service-broker
spec:
  template:
    spec:
      containers:
        - name: crossplane-service-broker
          image: $E2E_IMAGE
