name: E2E

on:
  pull_request:
    branches:
      - master

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - kind-node-version: v1.20.0
    steps:
      - uses: actions/checkout@v3
      - name: Determine Go version from go.mod
        run: echo "GO_VERSION=$(grep "go 1." go.mod | cut -d " " -f 2)" >> $GITHUB_ENV
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run e2e tests
        run: make e2e-test -e KIND_NODE_VERSION=${{ matrix.kind-node-version }} -e KIND_KUBECTL_ARGS=--validate=false -e bats_args="--report-formatter junit"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: "**/e2e/report.xml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: e2e-report (${{ matrix.kind-node-version }}
