name: Release
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: docker.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v2
      - name: Set version latest
        if: github.ref == 'refs/heads/master'
        run: echo "VERSION=latest" >> ${GITHUB_ENV}
      - name: Set version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> ${GITHUB_ENV}
      - name: Build Image
        run: make docker
        env:
          IMAGE_NAME: "${IMAGE}:${VERSION}"
      - name: Push Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login docker.io --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
          docker push "${IMAGE}:${VERSION}"
