name: Pull Request
on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Build image
        run: make docker
